title: Naughty and Nice
hero_image: images/banner.png
description: A sentiment analysis bot using Twitter
theme: red
duration: 3
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-4, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "python"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Step title
